<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\MechanicShop.Application\MechanicShop.Application.csproj" />
    <ProjectReference Include="..\..\Src\MechanicShop.Domain\MechanicShop.Domain.csproj" />
    <ProjectReference Include="..\..\Src\MechanicShop.Infrastructure\MechanicShop.Infrastructure.csproj" />
  </ItemGroup>

</Project>